import '../_shared/styles/global.css';

import type { Metadata } from 'next';
import localFont from 'next/font/local';

import ReactQueryProvider from '@/_shared/providers/ReactQueryProv';

const roboto = localFont({
  src: [
    {
      path: '../_shared/fonts/Roboto/Roboto-Variable.ttf',
      weight: '100 900',
      style: 'normal',
    },
    {
      path: '../_shared/fonts/Roboto/Roboto-Italic-Variable.ttf',
      weight: '100 900',
      style: 'italic',
    },
  ],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReactQueryProvider>
        <body className={`${roboto.className} antialiased`}>{children}</body>
      </ReactQueryProvider>
    </html>
  );
}
